/**
 * RBAC Configuration
 * Extracted from roles_permissions_config.json v9.5
 * Maps config role IDs to module permissions
 * © 2026 Mission Meets Tech
 */
import type { ModuleId } from '@/lib/supabase/types'

export interface ModulePermission {
  shouldRender: boolean
  canView: boolean
  canEdit: boolean
}

export interface RoleConfig {
  id: string
  displayName: string
  type: 'internal' | 'external'
  uiComplexityLevel: 'simplified' | 'standard' | 'advanced' | 'admin'
  modules: Record<ModuleId, ModulePermission>
}

/** All 12 roles from config v9.5 */
export const ROLES: Record<string, RoleConfig> = {
  executive: {
    id: 'executive',
    displayName: 'Executive / Admin',
    type: 'internal',
    uiComplexityLevel: 'admin',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: true, canView: true, canEdit: true },
      proposals: { shouldRender: true, canView: true, canEdit: true },
      pricing: { shouldRender: true, canView: true, canEdit: false },
      strategy: { shouldRender: true, canView: true, canEdit: true },
      blackhat: { shouldRender: true, canView: true, canEdit: true },
      compliance: { shouldRender: true, canView: true, canEdit: false },
      workflow_board: { shouldRender: true, canView: true, canEdit: true },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: true, canView: true, canEdit: false },
      admin: { shouldRender: true, canView: true, canEdit: true },
      integrations: { shouldRender: true, canView: true, canEdit: true },
      audit_log: { shouldRender: true, canView: true, canEdit: false },
    },
  },
  operations: {
    id: 'operations',
    displayName: 'Operations / COO',
    type: 'internal',
    uiComplexityLevel: 'advanced',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: true, canView: true, canEdit: true },
      proposals: { shouldRender: true, canView: true, canEdit: true },
      pricing: { shouldRender: true, canView: true, canEdit: true },
      strategy: { shouldRender: true, canView: true, canEdit: true },
      blackhat: { shouldRender: true, canView: true, canEdit: true },
      compliance: { shouldRender: true, canView: true, canEdit: false },
      workflow_board: { shouldRender: true, canView: true, canEdit: true },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: true, canView: true, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: true, canView: true, canEdit: false },
      audit_log: { shouldRender: true, canView: true, canEdit: false },
    },
  },
  capture_manager: {
    id: 'capture_manager',
    displayName: 'Capture Manager',
    type: 'internal',
    uiComplexityLevel: 'advanced',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: true, canView: true, canEdit: true },
      proposals: { shouldRender: true, canView: true, canEdit: true },
      pricing: { shouldRender: false, canView: false, canEdit: false },
      strategy: { shouldRender: true, canView: true, canEdit: true },
      blackhat: { shouldRender: true, canView: true, canEdit: true },
      compliance: { shouldRender: true, canView: true, canEdit: false },
      workflow_board: { shouldRender: true, canView: true, canEdit: true },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: true, canView: true, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
  proposal_manager: {
    id: 'proposal_manager',
    displayName: 'Proposal Manager',
    type: 'internal',
    uiComplexityLevel: 'standard',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: true, canView: true, canEdit: false },
      proposals: { shouldRender: true, canView: true, canEdit: true },
      pricing: { shouldRender: false, canView: false, canEdit: false },
      strategy: { shouldRender: true, canView: true, canEdit: false },
      blackhat: { shouldRender: false, canView: false, canEdit: false },
      compliance: { shouldRender: true, canView: true, canEdit: true },
      workflow_board: { shouldRender: true, canView: true, canEdit: true },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: false, canView: false, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
  solution_architect: {
    id: 'solution_architect',
    displayName: 'Solution Architect',
    type: 'internal',
    uiComplexityLevel: 'standard',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: true, canView: true, canEdit: false },
      proposals: { shouldRender: true, canView: true, canEdit: true },
      pricing: { shouldRender: false, canView: false, canEdit: false },
      strategy: { shouldRender: true, canView: true, canEdit: true },
      blackhat: { shouldRender: false, canView: false, canEdit: false },
      compliance: { shouldRender: true, canView: true, canEdit: false },
      workflow_board: { shouldRender: true, canView: true, canEdit: false },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: false, canView: false, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
  pricing_lead: {
    id: 'pricing_lead',
    displayName: 'Pricing Lead',
    type: 'internal',
    uiComplexityLevel: 'standard',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: true, canView: true, canEdit: false },
      proposals: { shouldRender: true, canView: true, canEdit: false },
      pricing: { shouldRender: true, canView: true, canEdit: true },
      strategy: { shouldRender: false, canView: false, canEdit: false },
      blackhat: { shouldRender: false, canView: false, canEdit: false },
      compliance: { shouldRender: true, canView: true, canEdit: false },
      workflow_board: { shouldRender: true, canView: true, canEdit: false },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: false, canView: false, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
  contracts_lead: {
    id: 'contracts_lead',
    displayName: 'Contracts Lead',
    type: 'internal',
    uiComplexityLevel: 'standard',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: true, canView: true, canEdit: false },
      proposals: { shouldRender: true, canView: true, canEdit: false },
      pricing: { shouldRender: true, canView: true, canEdit: false },
      strategy: { shouldRender: false, canView: false, canEdit: false },
      blackhat: { shouldRender: false, canView: false, canEdit: false },
      compliance: { shouldRender: true, canView: true, canEdit: true },
      workflow_board: { shouldRender: true, canView: true, canEdit: false },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: false, canView: false, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
  delivery_lead: {
    id: 'delivery_lead',
    displayName: 'Delivery Lead',
    type: 'internal',
    uiComplexityLevel: 'standard',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: true, canView: true, canEdit: false },
      proposals: { shouldRender: true, canView: true, canEdit: true },
      pricing: { shouldRender: false, canView: false, canEdit: false },
      strategy: { shouldRender: false, canView: false, canEdit: false },
      blackhat: { shouldRender: false, canView: false, canEdit: false },
      compliance: { shouldRender: false, canView: false, canEdit: false },
      workflow_board: { shouldRender: true, canView: true, canEdit: true },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: false, canView: false, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
  quality_lead: {
    id: 'quality_lead',
    displayName: 'Quality Lead',
    type: 'internal',
    uiComplexityLevel: 'standard',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: true, canView: true, canEdit: false },
      proposals: { shouldRender: true, canView: true, canEdit: false },
      pricing: { shouldRender: false, canView: false, canEdit: false },
      strategy: { shouldRender: false, canView: false, canEdit: false },
      blackhat: { shouldRender: false, canView: false, canEdit: false },
      compliance: { shouldRender: true, canView: true, canEdit: true },
      workflow_board: { shouldRender: true, canView: true, canEdit: false },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: false, canView: false, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
  author: {
    id: 'author',
    displayName: 'Author / SME',
    type: 'internal',
    uiComplexityLevel: 'simplified',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: false, canView: false, canEdit: false },
      proposals: { shouldRender: true, canView: true, canEdit: true },
      pricing: { shouldRender: false, canView: false, canEdit: false },
      strategy: { shouldRender: false, canView: false, canEdit: false },
      blackhat: { shouldRender: false, canView: false, canEdit: false },
      compliance: { shouldRender: false, canView: false, canEdit: false },
      workflow_board: { shouldRender: true, canView: true, canEdit: false },
      ai_chat: { shouldRender: true, canView: true, canEdit: true },
      documents: { shouldRender: true, canView: true, canEdit: true },
      analytics: { shouldRender: false, canView: false, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
  partner: {
    id: 'partner',
    displayName: 'Partner / Teaming',
    type: 'external',
    uiComplexityLevel: 'simplified',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: false, canView: false, canEdit: false },
      proposals: { shouldRender: true, canView: true, canEdit: true },
      pricing: { shouldRender: false, canView: false, canEdit: false },
      strategy: { shouldRender: false, canView: false, canEdit: false },
      blackhat: { shouldRender: false, canView: false, canEdit: false },
      compliance: { shouldRender: false, canView: false, canEdit: false },
      workflow_board: { shouldRender: false, canView: false, canEdit: false },
      ai_chat: { shouldRender: false, canView: false, canEdit: false },
      documents: { shouldRender: true, canView: true, canEdit: false },
      analytics: { shouldRender: false, canView: false, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
  viewer: {
    id: 'viewer',
    displayName: 'Viewer (Read Only)',
    type: 'external',
    uiComplexityLevel: 'simplified',
    modules: {
      dashboard: { shouldRender: true, canView: true, canEdit: false },
      pipeline: { shouldRender: false, canView: false, canEdit: false },
      proposals: { shouldRender: true, canView: true, canEdit: false },
      pricing: { shouldRender: false, canView: false, canEdit: false },
      strategy: { shouldRender: false, canView: false, canEdit: false },
      blackhat: { shouldRender: false, canView: false, canEdit: false },
      compliance: { shouldRender: false, canView: false, canEdit: false },
      workflow_board: { shouldRender: false, canView: false, canEdit: false },
      ai_chat: { shouldRender: false, canView: false, canEdit: false },
      documents: { shouldRender: true, canView: true, canEdit: false },
      analytics: { shouldRender: false, canView: false, canEdit: false },
      admin: { shouldRender: false, canView: false, canEdit: false },
      integrations: { shouldRender: false, canView: false, canEdit: false },
      audit_log: { shouldRender: false, canView: false, canEdit: false },
    },
  },
}
