import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { resolveRole, hasPermission } from '@/lib/rbac/config'
import { Breadcrumb } from '@/components/layout/Breadcrumb'

function formatDate(dateStr: string | null): string {
  if (!dateStr) return '—'
  return new Date(dateStr).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })
}

function difficultyStyle(d: string | null): string {
  switch (d?.toLowerCase()) {
    case 'hard':
      return 'bg-red-500/15 text-red-300'
    case 'medium':
      return 'bg-amber-500/15 text-amber-300'
    case 'easy':
      return 'bg-emerald-500/15 text-emerald-300'
    default:
      return 'bg-slate-500/15 text-slate-300'
  }
}

export default async function QuestionBankPage() {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: profile } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .single()

  const role = resolveRole(profile?.role)
  if (!hasPermission(role, 'admin', 'canView')) return null

  const { data: questions } = await supabase
    .from('orals_questions')
    .select(
      'id, question, suggested_answer, category, difficulty, source, tags, times_asked, avg_score, opportunity_id, created_at'
    )
    .order('category', { ascending: true })
    .order('created_at', { ascending: false })
    .limit(200)

  // Fetch opportunity titles for linked questions
  const oppIds = Array.from(
    new Set(
      (questions ?? [])
        .map((q) => q.opportunity_id)
        .filter((id): id is string => !!id)
    )
  )

  let oppMap: Record<string, string> = {}
  if (oppIds.length > 0) {
    const { data: opps } = await supabase
      .from('opportunities')
      .select('id, title')
      .in('id', oppIds)

    oppMap = Object.fromEntries((opps ?? []).map((o) => [o.id, o.title]))
  }

  const items = questions ?? []

  // Group by category
  const categories = new Map<string, typeof items>()
  for (const q of items) {
    const cat = q.category || 'Uncategorized'
    if (!categories.has(cat)) categories.set(cat, [])
    categories.get(cat)!.push(q)
  }

  return (
    <div className="space-y-6">
      <Breadcrumb
        items={[{ label: 'Admin', href: '/admin' }, { label: 'Question Bank' }]}
      />

      <div>
        <h1 className="text-2xl font-bold text-white">Question Bank</h1>
        <p className="mt-1 text-sm text-gray-500">
          Library of orals prep questions organized by category. Questions are
          generated by the AI Orals Coach and can be reused across
          opportunities.
        </p>
      </div>

      <div className="flex items-center gap-4 text-xs text-muted-foreground">
        <span>{items.length} questions</span>
        <span>{categories.size} categories</span>
      </div>

      {items.length === 0 ? (
        <div className="rounded-lg border border-border p-12 text-center">
          <p className="text-sm text-muted-foreground">
            No questions in the library yet. Generate questions using the Orals
            Coach on an opportunity page.
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {Array.from(categories.entries()).map(([cat, catQuestions]) => (
            <div key={cat}>
              <h2 className="mb-3 text-sm font-semibold uppercase tracking-wider text-gray-400">
                {cat}{' '}
                <span className="text-gray-600">({catQuestions.length})</span>
              </h2>
              <div className="divide-y divide-border rounded-lg border border-border">
                {catQuestions.map((q) => {
                  const tags = Array.isArray(q.tags) ? q.tags : []
                  return (
                    <div key={q.id} className="p-4 space-y-2">
                      <div className="flex items-start justify-between">
                        <p className="text-sm font-medium text-white flex-1">
                          {q.question}
                        </p>
                        <div className="ml-3 flex items-center gap-2">
                          {q.difficulty && (
                            <span
                              className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${difficultyStyle(
                                q.difficulty
                              )}`}
                            >
                              {q.difficulty}
                            </span>
                          )}
                        </div>
                      </div>

                      {q.suggested_answer && (
                        <p className="text-xs text-gray-400 bg-gray-900/30 rounded p-2">
                          {q.suggested_answer}
                        </p>
                      )}

                      <div className="flex items-center gap-3 text-[10px] text-gray-500">
                        {q.source && <span>Source: {q.source}</span>}
                        {q.times_asked != null && q.times_asked > 0 && (
                          <span>Asked {q.times_asked}x</span>
                        )}
                        {q.avg_score != null && (
                          <span>Avg Score: {q.avg_score.toFixed(1)}</span>
                        )}
                        {q.opportunity_id && oppMap[q.opportunity_id] && (
                          <span>Opp: {oppMap[q.opportunity_id]}</span>
                        )}
                        <span>{formatDate(q.created_at)}</span>
                      </div>

                      {tags.length > 0 && (
                        <div className="flex flex-wrap gap-1">
                          {tags.map((tag, i) => (
                            <span
                              key={i}
                              className="rounded bg-gray-800 px-1.5 py-0.5 text-[10px] text-gray-400"
                            >
                              {tag}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  )
                })}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
